version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: book_service
      POSTGRES_USER: POSTGRES_USER # Replace user with postgres
      POSTGRES_PASSWORD: POSTGRES_PASSWORD # Password with user's(postgres) password
    ports:
      - "5432:5432"